1. データの取得場所
 1.  https://currencylayer.com/signup/free
 1.  https://info.finance.yahoo.co.jp/fx/detail/?code=ZARJPY=FX
 1.  http://www.algo-fx-blog.com/fx-api-complete-guide-for-python-users/
 1.  CSVは下記サイトのからダウンロード
     https://stooq.com/q/d/?s=zarjpy
1. 前処理のメモ
  1. 当日の結果は、close/openの比率で判断する
  1. 過去の結果は、過去のオープン/当日のオープンで計算する

In [17]:
import pandas as pd

pram_predict_days=     [-5,-3,-2,-1]   #予想日(-1,-2,-3,-5日後)
pram_predict_percents= [0.5,1,2,3]   #数日後の何パーセント上昇するかを当てる(+0.5,1,2,3%)
pram_predict_day=1
pram_predict_percent=0.5
YEAR=""

start_date='2000-01-01'             #元データを2000年からにする

In [18]:
class load_csv:
    import pandas as pd
    
    def load(self):
        df_fx=pd.read_csv('data/zarjpy_d.csv')
        
        #df_fx=df_fx.ix[:,['日付け','終値','始値']]
        #df_fx.rename(columns={'Date':'日付け','Open':'始値','Close':'終値'},inplace=True)

        df_fx_len=len(df_fx)                #長さ
        print ("配列長さ:",df_fx_len)
        df_fx.head(1)
        return df_fx

In [19]:
def result(day0,xday):     #day0 当日の株価の上昇率の結果を返す
    rate=0  #上昇率
    if ((i-xday)>=0 and data_len>(i-xday)): 
        
        rate= ((df_fx.iloc[i,close_index]/df_fx.iloc[i,open_index])-1)*100
        
    return rate


def persent(day0,xday):     #day0 当日の株価
    rate=0  #上昇率
    if ((i-xday)>=0 and data_len>(i-xday)):        
        rate= ((df_fx.iloc[i,open_index]/df_fx.iloc[i-xday,open_index])-1)*100
        if rate <0:
            rate=0
        #rate=np.log10(rate)
    return rate

def persent_minus(day0,xday):     #day0 当日の株価
    rate=0  #上昇率
    if ((i-xday)>=0 and data_len>(i-xday)):        
        rate= ((df_fx.iloc[i,open_index]/df_fx.iloc[i-xday,open_index])-1)*100
        if rate>0:
            rate=0
        #rate=np.log10(rate)
    return rate

In [20]:
LOAD_CSV=load_csv()
df_fx=LOAD_CSV.load()
df_fx=df_fx.sort_values(by='Date')

df_fx=df_fx[(df_fx['Date']>start_date )]


df_fx = df_fx.reset_index(drop=True)
data_len=len(df_fx)

df_fx.head()

配列長さ: 7479

         Date    Open    High     Low   Close
0  2000-01-03  16.638  16.638  16.638  16.638
1  2000-01-04  16.899  16.899  16.899  16.899
2  2000-01-05  17.008  17.008  17.008  17.008
3  2000-01-06  17.211  17.211  17.211  17.211
4  2000-01-07  17.368  17.368  17.368  17.368

In [21]:
df_fx[df_fx['Date']=='2018-08-01']

            Date    Open     High      Low    Close
4730  2018-08-01  8.4524  8.50297  8.37862  8.45373

In [22]:
df=pd.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)
df = pd.DataFrame(index=['Date'], columns=[
"Date" ,"Close","Open",
"day+1" ,"day+2" ,"day+3",
"day+4" ,"day+5" ,"day+6",
"day+7" ,"day+8" ,"day+9",
"day+10","day+11","day+12",
"day+13","day+14","day+15",
"day+16","day+17","day+18",
"day+19","day+20","day+21",
"day+22","day+23","day+24",
"day+25","day+26","day+27",
"day+28","day+29","day+30",

"day-1" ,"day-2" ,"day-3",
"day-4" ,"day-5" ,"day-6",
"day-7" ,"day-8" ,"day-9",
"day-10","day-11","day-12",
"day-13","day-14","day-15",
"day-16","day-17","day-18",
"day-19","day-20","day-21",
"day-22","day-23","day-24",
"day-25","day-26","day-27",
"day-28","day-29","day-30",

"label_up","label_none","label_down",
"label2_up","label2_down"

])

In [23]:
close_index=df_fx.columns.get_loc('Close')
open_index=df_fx.columns.get_loc('Open')
date_index=df_fx.columns.get_loc('Date')

In [24]:
    for i in range(data_len) :
        Date_day=df_fx.iloc[i,date_index ]
        
        if i%100==0:
            print('{0:.1%}'.format(i/data_len),end=" ")
        
        #当日のOPENの株価
        day0         =df_fx.iloc[i,open_index]
        day0_open    =df_fx.iloc[i,open_index] 
        day0_close   =df_fx.iloc[i,close_index] 
        
        #その後の結果から正解ラベルを作成
        label_up=0     #上昇
        label_none=0   #変化少ない
        label_down=0   #下降
        label2_up=0    #上昇
        label2_down=0   #下降
        
        #正解データの計算  (pram_predict_day) 日後に、(pram_predict_persent)％の前後がある
        prediction=result(day0,pram_predict_day)    
      
        # ３つのらべるの場合
        if prediction>=pram_predict_percent:
            label_up=1          #上昇
            label_none=0        #そのまま
            label_down=0        #下降
        elif prediction<=(-1*pram_predict_percent):
            label_up=0          #上昇
            label_none=0        #そのまま
            label_down=1        #下降
        else:
            label_up=0          #上昇
            label_none=1        #そのまま
            label_down=0        #下降
            
            
        # 2つのらべるの場合
        if prediction>=0:
            label2_up=1          #上昇
            label2_down=0        #下降
        else:
            label2_up=0          #上昇
            label2_down=1        #下降
     
            
            
        series=pd.Series([Date_day,day0_close,day0_open,
                          
                          persent(day0,1),persent(day0,2),persent(day0,3),
                          persent(day0,4),persent(day0,5),persent(day0,6),
                          persent(day0,7),persent(day0,8),persent(day0,9),
                          persent(day0,10),persent(day0,11),persent(day0,12),
                          persent(day0,13),persent(day0,14),persent(day0,15),
                          persent(day0,16),persent(day0,17),persent(day0,18),
                          persent(day0,19),persent(day0,20),persent(day0,21),
                          persent(day0,22),persent(day0,23),persent(day0,24),
                          persent(day0,25),persent(day0,26),persent(day0,27),
                          persent(day0,28),persent(day0,29),persent(day0,30),

                          persent_minus(day0,1),persent_minus(day0,2),persent_minus(day0,3),
                          persent_minus(day0,4),persent_minus(day0,5),persent_minus(day0,6),
                          persent_minus(day0,7),persent_minus(day0,8),persent_minus(day0,9),
                          persent_minus(day0,10),persent_minus(day0,11),persent_minus(day0,12),
                          persent_minus(day0,13),persent_minus(day0,14),persent_minus(day0,15),
                          persent_minus(day0,16),persent_minus(day0,17),persent_minus(day0,18),
                          persent_minus(day0,19),persent_minus(day0,20),persent_minus(day0,21),
                          persent_minus(day0,22),persent_minus(day0,23),persent_minus(day0,24),
                          persent_minus(day0,25),persent_minus(day0,26),persent_minus(day0,27),
                          persent_minus(day0,28),persent_minus(day0,29),persent_minus(day0,30),
                          label_up,label_none,label_down,
                          label2_up,label2_down
                         ]
                          ,index=df.columns)
        series.append
        df=df.append(series,ignore_index = True)

#前処理データの保存
df.to_csv('data/fx.csv',index=False)

0.0% 2.1% 4.1% 6.2% 8.3% 10.3% 12.4% 14.5% 16.5% 18.6% 20.7% 22.7% 24.8% 26.9% 28.9% 31.0% 33.1% 35.1% 37.2% 39.3% 41.3% 43.4% 45.5% 47.5% 49.6% 51.7% 53.7% 55.8% 57.9% 59.9% 62.0% 64.1% 66.1% 68.2% 70.3% 72.3% 74.4% 76.5% 78.5% 80.6% 82.7% 84.7% 86.8% 88.9% 90.9% 93.0% 95.1% 97.1% 99.2%

In [29]:
df[df['Date']=='2018-08-31']

,Date,Close,Open,day+1,day+2,day+3,day+4,day+5,day+6,day+7,...,day-26,day-27,day-28,day-29,day-30,label_up,label_none,label_down,label2_up,label2_down
4753,2018-08-31,7.5644,7.55184,0,0,0,0,0,0,0,...,-10.8457,-9.87935,-8.66094,-9.17615,-9.11756,0,1,0,1,0

In [28]:
df

,Date,Close,Open,day+1,day+2,day+3,day+4,day+5,day+6,day+7,...,day-26,day-27,day-28,day-29,day-30,label_up,label_none,label_down,label2_up,label2_down
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000-01-03,16.63800,16.63800,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
2,2000-01-04,16.89900,16.89900,1.5687,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
3,2000-01-05,17.00800,17.00800,0.645009,2.22382,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
4,2000-01-06,17.21100,17.21100,1.19356,1.84626,3.44392,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
5,2000-01-07,17.36800,17.36800,0.912207,2.11665,2.77531,4.38755,0,0,0,...,0,0,0,0,0,0,1,0,1,0
6,2000-01-10,17.17900,17.17900,0,0,1.00541,1.6569,3.25159,0,0,...,0,0,0,0,0,0,1,0,1,0
7,2000-01-11,17.36600,17.36600,1.08854,0,0.900587,2.10489,2.76348,4.37553,0,...,0,0,0,0,0,0,1,0,1,0
8,2000-01-12,17.45200,17.45200,0.495221,1.58915,0.483648,1.40027,2.61054,3.27238,4.89241,...,0,0,0,0,0,0,1,0,1,0
9,2000-01-13,17.47000,17.47000,0.10314,0.598871,1.69393,0.587287,1.50485,2.71637,3.3789,...,0,0,0,0,0,0,1,0,1,0
10,2000-01-14,17.40200,17.40200,0,0,0.207302,1.2981,0.195762,1.10976,2.31656,...,0,0,0,0,0,0,1,0,1,0
11,2000-01-17,17.34600,17.34600,0,0,0,0,0.972117,0,0.784382,...,0,0,0,0,0,0,1,0,1,0
12,2000-01-18,17.29100,17.29100,0,0,0,0,0,0.651959,0,...,0,0,0,0,0,0,1,0,1,0
13,2000-01-19,17.35200,17.35200,0.352785,0.0345901,0,0,0,0,1.00704,...,0,0,0,0,0,0,1,0,1,0
14,2000-01-20,17.32000,17.32000,0,0.167717,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
15,2000-01-21,17.13500,17.13500,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
16,2000-01-24,17.04300,17.04300,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
17,2000-01-25,17.21800,17.21800,1.02681,0.484389,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
18,2000-01-26,17.15500,17.15500,0,0.657161,0.11672,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
19,2000-01-27,16.99700,16.99700,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
20,2000-01-28,16.52400,16.52400,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
21,2000-01-31,16.94000,16.94000,2.51755,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
22,2000-02-01,17.18000,17.18000,1.41677,3.96998,1.07666,0.14573,0,0.803849,0.26262,...,0,0,0,0,0,0,1,0,1,0
23,2000-02-02,17.24900,17.24900,0.40163,1.82409,4.38756,1.48261,0.547945,0.180044,1.20871,...,0,0,0,0,0,0,1,0,1,0
24,2000-02-03,17.31800,17.31800,0.400023,0.80326,2.2314,4.80513,1.88857,0.95016,0.580788,...,0,0,0,0,0,0,1,0,1,0
25,2000-02-04,17.08500,17.08500,0,0,0,0.855962,3.39506,0.517738,0,...,0,0,0,0,0,0,1,0,1,0
26,2000-02-07,17.25600,17.25600,1.00088,0,0.0405821,0.442375,1.86541,4.42992,1.5238,...,0,0,0,0,0,0,1,0,1,0
27,2000-02-08,17.39500,17.39500,0.805517,1.81446,0.444624,0.846426,1.25146,2.68595,5.27112,...,0,0,0,0,0,0,1,0,1,0
28,2000-02-09,17.25300,17.25300,0,0,0.983319,0,0.0231898,0.424913,1.8477,...,0,0,0,0,0,0,1,0,1,0
29,2000-02-10,17.16100,17.16100,0,0,0,0.444835,0,0,0,...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4809,2018-11-19,8.03459,8.06271,0.582333,1.95882,2.32528,2.47262,1.55097,0,0,...,0,0,0,0,0,0,1,0,0,1
4810,2018-11-20,7.99733,8.03470,0,0.232908,1.60462,1.9698,2.11663,1.19818,0,...,0,0,0,0,0,0,1,0,0,1
4811,2018-11-21,8.12791,7.99705,0,0,0,1.1285,1.49197,1.63812,0.723969,...,0,0,0,0,0,1,0,0,1,0
4812,2018-11-22,8.21491,8.12626,1.61572,1.13956,0.788197,1.37512,2.76246,3.1318,3.28031,...,0,0,0,0,0,1,0,0,1,0
4813,2018-11-23,8.15582,8.21522,1.09472,2.72813,2.24675,1.89155,2.4849,3.88742,4.26081,...,0,0,0,0,0,0,0,1,0,1
4814,2018-11-26,8.16518,8.17413,0,0.589078,2.21432,1.73535,1.38192,1.9723,3.36781,...,0,0,0,0,0,0,1,0,0,1
4815,2018-11-27,8.17608,8.16194,0,0,0.43907,2.06189,1.58363,1.23073,1.82023,...,0,0,0,0,0,0,1,0,1,0
4816,2018-11-28,8.24878,8.17709,0.185618,0.0362118,0,0.625503,2.25133,1.77219,1.41863,...,0,0,0,0,0,1,0,0,1,0
4817,2018-11-29,8.30946,8.24886,0.877696,1.06494,0.914226,0.409484,1.50869,3.14879,2.66544,...,0,0,0,0,0,1,0,0,1,0
4818,2018-11-30,8.19334,8.30931,0.732829,1.61696,1.80558,1.65375,1.14531,2.25257,3.90469,...,0,0,0,0,0,0,0,1,0,1
4819,2018-12-03,8.31222,8.27055,0,0.262945,1.14295,1.33069,1.17958,0.673506,1.7756,...,0,0,0,0,0,1,0,0,1,0
4820,2018-12-04,8.14152,8.29837,0.336374,0,0.600204,1.48317,1.67154,1.51992,1.01215,...,0,0,0,0,0,0,0,1,0,1
4821,2018-12-05,8.17747,8.15031,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
4822,2018-12-06,8.02545,8.17925,0.355079,0,0,0,0,0.0264153,0.212082,...,0,0,0,0,0,0,0,1,0,1
4823,2018-12-07,7.94377,8.01964,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
4824,2018-12-10,7.88193,7.94030,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
4825,2018-12-11,7.91765,7.88158,0,0,0,0,0,0,0,...,-0.692368,0,0,0,0,0,1,0,1,0
4826,2018-12-12,8.02178,7.91807,0.462978,0,0,0,0,0,0,...,-0.978699,-0.232595,0,0,0,1,0,0,1,0
4827,2018-12-13,8.01747,8.03121,1.42888,1.89848,1.14492,0.144271,0,0,0,...,-0.165578,0,0,0,0,0,1,0,0,1
4828,2018-12-14,7.88134,8.01754,0,1.25624,1.72503,0.972759,0,0,0,...,-1.84687,-0.335507,0,0,0,0,0,1,0,1
4829,2018-12-17,7.84473,7.88166,0,0,0,0.00101502,0,0,0,...,-2.43683,-3.51036,-2.02461,-1.43403,-0.69136,0,1,0,0,1
4830,2018-12-18,7.84112,7.84438,0,0,0,0,0,0,0,...,-1.19893,-2.8983,-3.96675,-2.48803,-1.90025,0,1,0,0,1
4831,2018-12-19,7.82856,7.84049,0,0,0,0,0,0,0,...,-0.351671,-1.24793,-2.94646,-4.01437,-2.53638,0,1,0,0,1
4832,2018-12-20,7.73618,7.82915,0,0,0,0,0,0,0,...,-0.638874,-0.495796,-1.39076,-3.08683,-4.1532,0,0,1,0,1
4833,2018-12-21,7.60481,7.73611,0,0,0,0,0,0,0,...,-2.17127,-1.81966,-1.67828,-2.56261,-4.23852,0,0,1,0,1
4834,2018-12-24,7.57218,7.58917,0,0,0,0,0,0,0,...,-5.32508,-4.02943,-3.6845,-3.54581,-4.41334,0,1,0,0,1
4835,2018-12-26,7.64275,7.54017,0,0,0,0,0,0,0,...,-6.48095,-5.93636,-4.64907,-4.30637,-4.16857,1,0,0,1,0
4836,2018-12-27,7.66349,7.64041,1.32941,0.675173,0,0,0,0,0,...,-4.90734,-5.23769,-4.68586,-3.38147,-3.03421,0,1,0,1,0
4837,2018-12-28,7.64771,7.66287,0.293963,1.62728,0.971121,0,0,0,0,...,-4.17879,-4.6278,-4.95913,-4.40567,-3.09744,0,1,0,0,1
4838,2018-12-31,7.64661,7.65462,0,0.185985,1.51787,0.862413,0,0,0,...,-5.8039,-4.28195,-4.73048,-5.06145,-4.50859,0,1,0,0,1